---
- name: DotFiles Config
  hosts: localhost
  connection: local
  vars_files: vars/vault.yml

  pre_tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes # apt update
        cache_valid_time: 86400 # one day
      become: true

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - wget
          - zip
          - unzip
          - curl
          - htop
        state: latest
      become: true

  tasks:
    - name: Run all roles
      include_role:
        name: "{{ role }}"
      loop:
        - bash
        - bat
        - fonts
        - homebrew
        - nvim
        - tmux
      loop_control:
        loop_var: role
