---
- name: Atuin | Installation
  community.general.homebrew:
    name: atuin
    state: latest
    update_homebrew: yes

- name: Atuin | Config folder creation
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/atuin"
    state: directory

- name: Atuin | Copy dotfiles
  ansible.builtin.copy:
    src: config.toml
    dest: "{{ ansible_user_dir }}/.config/atuin/config.toml"
    force: true
